### ISSUE TITLE
Shield won't build with Crystal 0.36.1

### ISSUE THREAD

**Issue by BrucePerens** [GrottoPress/shield#34]
Shield won't build with the new Crystal release. This new version appears to detect duplicate named arguments better than before, OR duplicate named arguments are happening where they did not before. They appear to be duplicates in attribute lists that are passed to operations. You should be able to see the problems as soon as you attempt to build.

**Comment by akadusei** [comment]
You must be on *Lucky* `master`. *Shield* will support *Crystal* v0.36 when it is supported by *Lucky*, hopefully in the next version. I intend to begin work on this soon.
