### ISSUE TITLE
Monkey-patched Avram::SaveOperation calls before_save 4 times

### ISSUE THREAD

**Issue by BrucePerens** [GrottoPress/shield#6]
I have backed out the Avram monkey-patching of Avram::SaveOperation#save and Avram::SaveOperation#valid in my local version of Shield for now, because it calls my `before_save` code 4 times for one save. The monkey-patch calls it a few times, I think, and then calls `previous_def` and the unpatched version calls it at least once. Since Jeremy Woternik is actively working on Avram, it might be best for most of your changes to be PRs to him.

Although `before_save` is expected to be idempotent, because user code can call `valid?` as much as it likes, it can be arbitrarily expensive. The particular one I was debugging performs HTML sanitization.

**Comment by akadusei** [comment]
Thanks, Bruce. Your reports have been very helpful. It should be fixed now. You may use the `dev` branch to see if it breaks anything.

> Since Jeremy Woternik is actively working on Avram, it might be best for most of your changes to be PRs to him.

That has been the plan. Some have already been discussed or added to *Avram*. There's still few issues open for some of them. The rest will follow in due course.
